# Generated by Django 2.2.11 on 2020-04-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Name',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
